In [5]:
import numpy as np
import pandas as pd

In [31]:
df_employees = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104],
    'Name': ['Ashwini', 'sital', 'Savyata', 'Monika'],
    'Dept': ['Engineering', 'Marketing', 'Engineering', 'HR']
})

df_salaries = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 105],
    'Annual_Salary': [95000, 72000, 88000, 65000],
    'Bonus_Percent': [0.10, 0.05, 0.12, 0.08]
})

In [32]:
df_employees

   Emp_ID     Name         Dept
0     101  Ashwini  Engineering
1     102    sital    Marketing
2     103  Savyata  Engineering
3     104   Monika           HR

In [33]:
df_salaries

   Emp_ID  Annual_Salary  Bonus_Percent
0     101          95000           0.10
1     102          72000           0.05
2     103          88000           0.12
3     105          65000           0.08

In [34]:
# ON = IT MENTION, ON WHICH BASIS WE ARE COLUMNS WHICH ARE BOTH AVAILABLE IN DATAFRAMES
# HOW = INNNER 
#It only keeps rows where the "ID" (or name) exists in both DataFrames. If there isn't a match on both sides, the data is discarded.

In [35]:
pd.merge(df_employees,df_salaries , on = 'Emp_ID',how = 'inner')

   Emp_ID     Name         Dept  Annual_Salary  Bonus_Percent
0     101  Ashwini  Engineering          95000           0.10
1     102    sital    Marketing          72000           0.05
2     103  Savyata  Engineering          88000           0.12

In [36]:
# HOW = OUTER
#It keeps every single row from both DataFrames. If a match doesn't exist, pandas doesn't delete the row; instead,
#it fills the missing gaps with NaN (Not a Number).

In [37]:
pd.merge(df_employees,df_salaries , on = 'Emp_ID' , how = 'outer')

   Emp_ID     Name         Dept  Annual_Salary  Bonus_Percent
0     101  Ashwini  Engineering        95000.0           0.10
1     102    sital    Marketing        72000.0           0.05
2     103  Savyata  Engineering        88000.0           0.12
3     104   Monika           HR            NaN            NaN
4     105      NaN          NaN        65000.0           0.08

In [38]:
#how='left'
#keeps everything from the first DataFrame (the one on the left) and only brings in data 
#from the second DataFrame where there is a match.
pd.merge(df_employees,df_salaries , on = 'Emp_ID' , how = 'left')

   Emp_ID     Name         Dept  Annual_Salary  Bonus_Percent
0     101  Ashwini  Engineering        95000.0           0.10
1     102    sital    Marketing        72000.0           0.05
2     103  Savyata  Engineering        88000.0           0.12
3     104   Monika           HR            NaN            NaN

In [39]:
# how='right' 
#is the exact opposite. It keeps everything from the second DataFrame and only pulls in 
#info from the first one if it fits.
pd.merge(df_employees,df_salaries , on = 'Emp_ID' , how = 'right')

   Emp_ID     Name         Dept  Annual_Salary  Bonus_Percent
0     101  Ashwini  Engineering          95000           0.10
1     102    sital    Marketing          72000           0.05
2     103  Savyata  Engineering          88000           0.12
3     105      NaN          NaN          65000           0.08

In [40]:
#CONCATINATION OF 2 DATAFRAMES
# WE SHOULD USE ( PD.CONCAT)
# IF WE WANT TO CONCATINATE THE THE DATAFARAMES ON THE BASIS OF ROWS AND COLUM THEN WE SHOULD USE THE AXIS..
#FOR ROW (AXIS= 1)
#FOR COLUMN (AXIS =0)

In [43]:
pd.concat([df_employees,df_salaries] , axis = 1)

   Emp_ID     Name         Dept  Emp_ID  Annual_Salary  Bonus_Percent
0     101  Ashwini  Engineering     101          95000           0.10
1     102    sital    Marketing     102          72000           0.05
2     103  Savyata  Engineering     103          88000           0.12
3     104   Monika           HR     105          65000           0.08

In [44]:
pd.concat([df_employees,df_salaries], axis = 0)

   Emp_ID     Name         Dept  Annual_Salary  Bonus_Percent
0     101  Ashwini  Engineering            NaN            NaN
1     102    sital    Marketing            NaN            NaN
2     103  Savyata  Engineering            NaN            NaN
3     104   Monika           HR            NaN            NaN
0     101      NaN          NaN        95000.0           0.10
1     102      NaN          NaN        72000.0           0.05
2     103      NaN          NaN        88000.0           0.12
3     105      NaN          NaN        65000.0           0.08

In [46]:
#JONINNG OF 2 DATAFRAMES 
#Joining is a specific way to combine two DataFrames based on their indexes rather than columns.

In [54]:
students = pd.DataFrame({
    'Names': ['Leo', 'Mia', 'Max'],
    'Grade': ['5th', '6th', '5th']
})
fees = pd.DataFrame({
    'Name': ['Leo', 'Max', 'Sam'],
    'Paid': ['Yes', 'Yes', 'Yes']
})

In [56]:
#Inner Join is a "Match-Only" list (it only keeps items found in both),

students.join(fees, how = 'inner')

  Names Grade Name Paid
0   Leo   5th  Leo  Yes
1   Mia   6th  Max  Yes
2   Max   5th  Sam  Yes

In [60]:
#while Outer Join is a "Master" list (it keeps everything from both, even if they don't match).
fees.join(students, how = 'outer')

  Name Paid Names Grade
0  Leo  Yes   Leo   5th
1  Max  Yes   Mia   6th
2  Sam  Yes   Max   5th