In [2]:
import numpy as np
import pandas as pd

In [40]:
#fillna = COLUMN WISE
#DROP = ROW WISE
#LOC( SELECTION0 = COLUMM
#FILL= column

In [3]:
#FINDING THE MISSING DATAS

In [13]:
data = {
    'Name': ['Ashwini', 'Ashwinii', 'Ashwiniii', 'Ramesh', np.nan, 'Sita'],
    'Age': [22, np.nan, 24, 25, 21, np.nan],
    'Salary': [60000, 80000, np.nan, 45000, 70000, 55000],
    'City': ['Kathmandu', np.nan, 'Boston', 'Pokhara', np.nan, 'Kathmandu']
}
df=pd.DataFrame(data)

In [15]:
df

        Name   Age   Salary       City
0    Ashwini  22.0  60000.0  Kathmandu
1   Ashwinii   NaN  80000.0        NaN
2  Ashwiniii  24.0      NaN     Boston
3     Ramesh  25.0  45000.0    Pokhara
4        NaN  21.0  70000.0        NaN
5       Sita   NaN  55000.0  Kathmandu

In [16]:
# IF WE WANT TO SEE IF THERE IS NULL VALUE...IN BOOLEAN VALUE( TRUE OR FALSE)
df.isna()

    Name    Age  Salary   City
0  False  False   False  False
1  False   True   False   True
2  False  False    True  False
3  False  False   False  False
4   True  False   False   True
5  False   True   False  False

In [17]:
#IF WE WANT TO SUM UP 
#TO FIND HOW MANY NULL VALUES ARE THERE IN ROWS
df.isna().sum()

Name      1
Age       2
Salary    1
City      2
dtype: int64

In [18]:
#IF WE WANT TO SEE IF EVERY COLUMN CONSIST OF NULL VAUES OR NOT
df.isna().any()

Name      True
Age       True
Salary    True
City      True
dtype: bool

In [19]:
# REMOVING THE MISSING DATA

In [21]:
#WHEN WE ARE REMOVING THE MISSING DATA IT WORKS ON THE ROW BASIS
df.dropna()

      Name   Age   Salary       City
0  Ashwini  22.0  60000.0  Kathmandu
3   Ramesh  25.0  45000.0    Pokhara

In [31]:
#WE USE THRESHHOLS TO HAVE  A CONDIDTION 
# HERE WE CHECK IF ANY ROW HAVE ATLEAST 3  NON NULL VALUE THESN EXCEPT IT REMOVE ALL OTHER
df.dropna(thresh = 4)

      Name   Age   Salary       City
0  Ashwini  22.0  60000.0  Kathmandu
3   Ramesh  25.0  45000.0    Pokhara

In [32]:
#FILLING THE MISSING DATA

In [33]:
#FOR REPLACING THE MSIIING NUMERIC MISSING VALUE WE REPLACE WITH 0.
# df.fill(0)---its not enought to keep change permanantly so inorder to keep
#the 0 in missing values we have to use of inplace(inplace = true)

In [35]:
df.fillna(0)

        Name   Age   Salary       City
0    Ashwini  22.0  60000.0  Kathmandu
1   Ashwinii   0.0  80000.0          0
2  Ashwiniii  24.0      0.0     Boston
3     Ramesh  25.0  45000.0    Pokhara
4          0  21.0  70000.0          0
5       Sita   0.0  55000.0  Kathmandu

In [39]:
#filling nan with different values
#her ewe have string values where we cant put the numeric 0 for the missing value 
#so its best to write unkonwn in this case
values= {'Name':'unknown','Age':0, 'Salary':0, 'City':'unknown'}
df.fillna(values)

        Name   Age   Salary       City
0    Ashwini  22.0  60000.0  Kathmandu
1   Ashwinii   0.0  80000.0    unknown
2  Ashwiniii  24.0      0.0     Boston
3     Ramesh  25.0  45000.0    Pokhara
4    unknown  21.0  70000.0    unknown
5       Sita   0.0  55000.0  Kathmandu