PANDAS

In [1]:
# SERIES
#SERIES are the one dimensional labled array which is capable of holding any data types. the axis labels collectively called index.
#The series goes vertical listing not horizontal like array

import numpy as np
import pandas as pd
labels = ['helloo ', 'namaste', 'salammalikum']
list = [10, 20, 30]
arr = np.array (["ashwini","sital","sunita"])
dict = {10:20 , 30:40, 60:70}

In [2]:
pd.Series(arr, index = labels)

helloo          ashwini
namaste           sital
salammalikum     sunita
dtype: object

In [3]:
# when we call the dictonary in the series then insted of the index its key appear in the place of 
#the index and the values appers at  the the value
pd.Series(dict)

10    20
30    40
60    70
dtype: int64

In [4]:
# DATAFRAME
#WHEN YOU COMBINE THE MULTIPLE SERIES THEN ,IT IS CALLED DATAFRAME.
#It consists of multiple series but one indexing.
import numpy as np
import pandas as pd

In [5]:
#CREATING THE DATAFRAME
#WE CAN USE LIST,ARRAY,DICT ETC..TO CREATE A DATAFRAME.
#USING DICTONARY
data = {
    'Name':['Ashwini', 'Ashwina', 'Ashmina' ],
    'Age' :[21, 22, 23],
    'city' :['london', 'Boston', 'newyork'],
    'salary':[70000,80000,90000]
}
df = pd.DataFrame(data)

In [6]:
df

      Name  Age     city  salary
0  Ashwini   21   london   70000
1  Ashwina   22   Boston   80000
2  Ashmina   23  newyork   90000

In [7]:
 #USING LIST
data_list= [
    ['ashwini', 22,60000],
    ['ashwinii',23,80000],
    ['ashwiniii',24,100000]
]
df2 = pd.DataFrame(data_list)
columns = ['name', 'age','salary']
df2 = pd.DataFrame(data_list, columns=columns)

In [8]:
#there is no named in the column head cuz like dict itdoest have the key....
#If we want the dataframe  to have a column name then it we should pass here colum with comlumn name
df2

        name  age  salary
0    ashwini   22   60000
1   ashwinii   23   80000
2  ashwiniii   24  100000

In [16]:
df

      Name  Age     city  salary
0  Ashwini   21   london   70000
1  Ashwina   22   Boston   80000
2  Ashmina   23  newyork   90000

In [17]:
df['Name']

0    Ashwini
1    Ashwina
2    Ashmina
Name: Name, dtype: object

In [18]:
df[['Age','salary']]

   Age  salary
0   21   70000
1   22   80000
2   23   90000

In [20]:
#CREATING A NEW COLUMN
#IF WE WANT TO ADD A NEW COLUMN AND ADD VALUE ACCORDINT TO THE EXISTING ROWS.
df['designtion'] = ['doctor', 'engineer','pilot']

In [21]:
df

      Name  Age     city  salary designtion
0  Ashwini   21   london   70000     doctor
1  Ashwina   22   Boston   80000   engineer
2  Ashmina   23  newyork   90000      pilot

In [25]:
#REMOVING THE COLUMN
#FOR REMOVING THE COLUMN WE USE DROP
#FOR ACTUAL REMOVING WE USE THE KEYWORD "inplace"
#FOR REMOVING THE COLUMN WE USE AXIS= 1...AND FOR ROW WE USE AXIS=0

df.drop('designtion',axis=1)

      Name  Age     city  salary
0  Ashwini   21   london   70000
1  Ashwina   22   Boston   80000
2  Ashmina   23  newyork   90000

In [27]:
#ALTHOUGH WE REMOVED THE DESIGNITION COLUM USING DROP BUT IT STILL APPEARS CUZ IT NOT RELLY REMOVED.
# TO REMOVE 100% WE NEED TO USE inplace keyword
# df.drop ('desiginition', axis = 1 ,inplace = True)
df

      Name  Age     city  salary designtion
0  Ashwini   21   london   70000     doctor
1  Ashwina   22   Boston   80000   engineer
2  Ashmina   23  newyork   90000      pilot

In [29]:
df.loc[[1,2]]

      Name  Age     city  salary designtion
1  Ashwina   22   Boston   80000   engineer
2  Ashmina   23  newyork   90000      pilot

In [30]:
#SELECTING THE SUBSETS OF ROWS AND COLUMNS 
#FOR SELECTION ROWS AND THE COLUMN WE NEED TO MENTION FIRST ROWS USING 
# .loc WITH SELECTING THE INDEX NUMBER  AND THE SELECT THE COLUMN IN []
df.loc[[1,2]][['salary','designtion']]

   salary designtion
1   80000   engineer
2   90000      pilot

In [32]:
#CONDITIONAL SELECTION 
#CONDITIONAL IS SOMETHING LIKE(>, < , =, !=)
#EXAMPLE: IF I WANT TO PRINT THE NAME WHOSE AGE IS ABOVE 22 THEN.
df[df['Age']>22]

      Name  Age     city  salary designtion
2  Ashmina   23  newyork   90000      pilot

In [39]:
#using the And( &) operator.
#use the () to seperate the the two expressions 
df[(df['Age'] > 21) & (df['city'] == 'Boston')]

      Name  Age    city  salary designtion
1  Ashwina   22  Boston   80000   engineer

In [ ]:
#MISSING DATAS